server:
  port: 8091

spring:
  application:
    name: employee-api-advanced

  # PostgreSQL (porta 5433 para n찾o conflitar com o demo)
  datasource:
    url: jdbc:postgresql://localhost:5433/employeedb
    username: employee
    password: employee123
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      # TODO 5: Ap처s criar as migrations Flyway, mude para "validate"
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # Flyway
  # TODO 5: Habilite o Flyway descomentando as linhas abaixo
  #         e mude ddl-auto para "validate"
  flyway:
    enabled: false
    # enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # RabbitMQ (porta 5673 para n찾o conflitar com o demo)
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

  # Redis (porta 6380 para n찾o conflitar com o demo)
  data:
    redis:
      host: localhost
      port: 6380

  # Cache
  # TODO 8: Habilite o cache Redis descomentando a linha abaixo
  cache:
    type: none
    # type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.example.employee: DEBUG
